FROM rust:1.68-bullseye

RUN apt-get update && \
    apt-get -y install git protobuf-compiler && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    rustup update

RUN alias protoc='protoc $1 --experimental_allow_proto3_optional'

# ready to shuttle
RUN cargo install cargo-shuttle