name: Deployment to shuttle

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: build
        uses: docker/build-push-action@v4
        with:
          file: docker/rust/Dockerfile.release
          tags: shuttleapp
          push: false
      
      - name: run
        uses: addnab/docker-run-action@v3
        with:
          image: shuttleapp
          run: |
            cargo --version
            cargo shuttle --version
